version: '3'

services:
  database:
    image: mysql:5.7
    volumes:
      - ./sql_dump/Quizbot_data.sql:/docker-entrypoint-initdb.d/initdb.sql
      #- sql_volume:/var/lib/mysql
    ports:
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=${SQLPASS}

  quizbot:
    build: .
    volumes:
      - .:/home
    ports:
      - 3000:3000
    restart: on-failure
    depends_on:
      - database

volumes:
  sql_volume: